exec bash ~/dwm/bar.sh &
xrdb -load ~/urxvt/pc.Xresources
exec dunst -conf ~/.config/dunst/dunst_desk &
exec picom &
exec feh --bg-fill ~/Изображения/wallhaven-grey.png &
exec blueman-applet &
exec dwm
